collab/collab/urls.py
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("task.urls")),
]

collab/task/urls.py
from django.urls import path

from task.views import TaskListView, TaskUpdateView

app_name = "task"

urlpatterns = [
    path('', TaskListView.as_view(),  name='home'),
    path('update/<int:pk>', TaskUpdateView.as_view(),  name='update-task'),
]

collab/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    ADMIN = 'admin'
    MANAGER = 'manager'
    GRAPHIC = 'graphic'
    WEB = 'web'
    DATABASE = 'database'

    TYPE_CHOICES = (
        (ADMIN, 'Admin',),
        (MANAGER, 'Manager',),
        (GRAPHIC, 'Graphic',),
        (WEB, 'Web',),
        (DATABASE, 'database',),
    )

    type = models.CharField(
        verbose_name='Type',
        max_length=255,
        default=ADMIN,
        choices=TYPE_CHOICES,
    )

collab/comment/models.py
from django.db import models


# Create your models here.
from task.models import Task


class Comment(models.Model):
    comment = models.TextField(null=True, blank=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')

collab/project/models.py
from django.db import models


# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=255, null=True, blank=False)
    budget = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True, default=0.0)

    def __str__(self):
        return str(self.title)

collab/task/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

from accounts.models import User
from project.models import Project


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.assignee.id, filename)


class Task(models.Model):
    PENDING = 'P'
    FEEDBACK = 'F'
    COMPLETED = 'C'

    STATUS_TYPE_CHOICES = (
        (PENDING, 'Pending',),
        (FEEDBACK, 'Feedback',),
        (COMPLETED, 'Completed',),

    )
    title = models.CharField(max_length=255, null=True, blank=False)
    description = models.CharField(max_length=255, null=True, blank=False)
    assignee = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS_TYPE_CHOICES, max_length=1, default=PENDING)
    deadline = models.DateField()
    upload = models.FileField(upload_to=user_directory_path)
    dependencies = models.ManyToManyField("self", blank=True)
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='tasks',
    )

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse('task:update-task', kwargs={'pk': self.pk})

collab/task/forms.py
from django import forms

from comment.models import Comment
from task.models import Task


class TaskUpdateForm(forms.ModelForm):
    comment = forms.CharField(max_length=255, required=False,
                              widget=forms.Textarea(
                                  attrs={"class": "form-control", "placeholder": "Your Comment"}

                              ),
                              )

    def __init__(self, *args, **kwargs):
        super(TaskUpdateForm, self).__init__(*args, **kwargs)
        self.fields['comment'].widget.attrs.update(
            {
                'placeholder': 'Your Comment',
            }
        )

    class Meta:
        model = Task
        fields = ['status', 'upload', 'comment']

    def save(self, commit=True):
        task = super(TaskUpdateForm, self).save(commit=False)
        if self.cleaned_data['comment'] != "" and commit:
            Comment.objects.create(task=self.instance, comment=self.cleaned_data['comment'])
        if commit:
            task.save()
        return task

collab/comment/views.py
from django.shortcuts import render

# Create your views here.

collab/project/views.py
from django.shortcuts import render

# Create your views here.

collab/task/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView

from .forms import TaskUpdateForm
from .models import Task


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    queryset = Task.objects.all()
    template_name = 'home.html'

    def get_queryset(self):
        qs = super(TaskListView, self).get_queryset()
        qs.filter(assignee=self.request.user).order_by('deadline')
        return qs


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskUpdateForm
    template_name = 'task_update_form.html'

    def get_queryset(self):
        qs = super(TaskUpdateView, self).get_queryset()
        qs.filter(assignee=self.request.user)
        return qs

collab/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!--Stylesheet-->

    <style media="screen">
        *,
        *:before,
        *:after {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            background-color: #080710;
        }

        .background {
            width: 430px;
            height: 520px;
            position: absolute;
            transform: translate(-50%, -50%);
            left: 50%;
            top: 50%;
        }

        .background .shape {
            height: 200px;
            width: 200px;
            position: absolute;
            border-radius: 50%;
        }

        .shape:first-child {
            background: linear-gradient(
                    #1845ad,
                    #23a2f6
            );
            left: -80px;
            top: -80px;
        }

        .shape:last-child {
            background: linear-gradient(
                    to right,
                    #ff512f,
                    #f09819
            );
            right: -30px;
            bottom: -80px;
        }

        form {
            height: 520px;
            width: 400px;
            background-color: rgba(255, 255, 255, 0.13);
            position: absolute;
            transform: translate(-50%, -50%);
            top: 50%;
            left: 50%;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
            padding: 50px 35px;
        }

        form * {
            font-family: 'Poppins', sans-serif;
            color: #ffffff;
            letter-spacing: 0.5px;
            outline: none;
            border: none;
        }

        form h3 {
            font-size: 32px;
            font-weight: 500;
            line-height: 42px;
            text-align: center;
        }

        label {
            display: block;
            margin-top: 30px;
            font-size: 16px;
            font-weight: 500;
        }

        input {
            display: block;
            height: 50px;
            width: 100%;
            background-color: rgba(255, 255, 255, 0.07);
            border-radius: 3px;
            padding: 0 10px;
            margin-top: 8px;
            font-size: 14px;
            font-weight: 300;
        }

        ::placeholder {
            color: #e5e5e5;
        }

        button {
            margin-top: 50px;
            width: 100%;
            background-color: #ffffff;
            color: #080710;
            padding: 15px 0;
            font-size: 18px;
            font-weight: 600;
            border-radius: 5px;
            cursor: pointer;
        }

        .social {
            margin-top: 30px;
            display: flex;
        }

        .social div {
            background: red;
            width: 150px;
            border-radius: 3px;
            padding: 5px 10px 10px 5px;
            background-color: rgba(255, 255, 255, 0.27);
            color: #eaf0fb;
            text-align: center;
        }

        .social div:hover {
            background-color: rgba(255, 255, 255, 0.47);
        }

        .social .fb {
            margin-left: 25px;
        }

        .social i {
            margin-right: 4px;
        }

    </style>
    <meta charset="utf-8">
    <title>{% block title %}Collab{% endblock %}</title>
</head>
<body>
<main class="container mt-3">
    {% block content %}
    {% endblock %}
</main>

{% block js %}

{% endblock js %}
</body>
</html>

collab/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Hi {{ user.username }}!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
                </li>
            </ul>
        </div>
    </nav>


    <div class="list-group">
        {% for task in object_list %}
            <a href="{% url "task:update-task" task.pk %}" class="list-group-item list-group-item-action">
                {{ task.title }} | {{ task.get_status_display }} | {{ task.deadline }}
            </a>
        {% empty %}
            <a href="#" class="list-group-item list-group-item-action">No tasks yet.</a>
        {% endfor %}
    </div>
{% endblock %}

collab/templates/task_update_form.html
{% extends 'base.html' %}

{% block title %}Task Updated{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Hi {{ user.username }}!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'task:home' %}">Home</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="card text-white bg-dark my-3 mx-auto" style="max-width: 18rem;">
        <div class="card-header text-center" onclick="toggleForm()">Update</div>
        <div class="card-body">
            <h5 class="card-title">{{ object.title }}</h5>
            <p class="card-text">{{ object.description }}</p>
            <h6>{{ object.get_status_display }} </h6>
            <h6>{{ object.deadline }} </h6>
        </div>
    </div>

    {% for comment in object.comments.all %}
        <div class="card text-center text-white bg-dark mb-3">
            <div class="card-body">
                <p class="card-text">{{ comment.comment }}</p>
            </div>
        </div>
    {% endfor %}

    <form method="post" enctype="multipart/form-data" id="form" style="height: 730px" hidden>{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

{% block js %}
    <script>
        const form = document.getElementById('form');

        function toggleForm() {
            form.hidden = !form.hidden;
        }
    </script>
{% endblock %}